archives:
    - format: zip
      name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
before:
    hooks:
        # - export sdk_version="v2.34.0" # go list -m github.com/hashicorp/terraform-plugin-sdk/v2 | awk '{print $2}'
        - go mod edit --replace github.com/hashicorp/terraform-plugin-sdk/v2=github.com/cloutierMat/terraform-plugin-sdk/v2@v2.34.0
        - go mod tidy
builds:
    - binary: "{{ .ProjectName }}_v{{ .Version }}"
      env:
          - CGO_ENABLED=0
      flags:
          - -trimpath
          - -v
      mod_timestamp: "{{ .CommitTimestamp }}"
      goos:
          - linux
          - darwin
      goarch:
          - amd64
          - arm64
      ignore:
          - goos: darwin
            goarch: "386"

checksum:
    algorithm: sha256
    extra_files:
        - glob: "terraform-registry-manifest.json"
          name_template: "{{ .ProjectName }}_{{ .Version }}_manifest.json"
    name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
release:
    extra_files:
        - glob: "terraform-registry-manifest.json"
          name_template: "{{ .ProjectName }}_{{ .Version }}_manifest.json"
signs:
    - artifacts: checksum
      args:
          # if you are using this in a GitHub action or some other automated pipeline, you
          # need to pass the batch flag to indicate its not interactive.
          - "--batch"
          - "--local-user"
          - "{{ .Env.GPG_FINGERPRINT }}" # set this environment variable for your signing key
          - "--output"
          - "${signature}"
          - "--detach-sign"
          - "${artifact}"